# Site settings
title: Kotis Style Guide
email: jay.fredlund@kotisdesign.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/style-guide" # the subpath of your site, e.g. /blog/
url: "http://kotisdesign.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ['strikethrough',
               'no_intra_emphasis', 'tables', 'autolink',
               'safe_links_only', 'no_styles', 'with_toc_data' ]

# SASS settings
sass:
  sass_dir: _assets/_css

highlighter: pygments
